organizationName = "diamondburned-testorg"

[validate]
trustedUsers = [ "diamondburned", "GitHub" ]
includedRepos = [ "/test[0-9]*/" ]
# excludedRepos = [ "autograde*" ]

[validate_html]
showNonTampered = false
