organizationName = "diamondburned-testorg"

[validate]
trustedUsers = [ "diamondburned", "GitHub" ]
includedRepos = [ "test*" ]
excludedRepos = [ "autograde*" ]

[validate_html]
showNonTampered = false
